### ISSUE TITLE
 Bintray Shutting Down May 2021 -- Host artifacts elsewhere?

### ISSUE THREAD

**Issue by russellbanks** [Droppers/AnimatedBottomBar#24]
Hi! A couple days ago JFrog (which owns Bintray/JCenter) announced that they're sunsetting Bintray/JCenter - the last day to access these repositories will be May 2021. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I know a lot of tooling goes into artifact upload to a repository, so I wanted to throw a signal flare up now so nobody is caught by surprise on May 1.

**Comment by Droppers** [comment]
Thank you! I did not know about this yet!

**Comment by RussellBanks** [comment]
Just checking in on this! Is there plans to migrate Animated Bottom Bar to another repository, such as Maven or Jitpack, etc?

**Comment by Droppers** [comment]
@RussellBanks

Its is already available on Jitpack, see https://jitpack.io/#Droppers/AnimatedBottomBar/1.0.9

When I have time I will migrate to Maven Central.

**Comment by jackdevey** [comment]
I've tried changing the dependency to Jitpack by replacing `implementation 'nl.joery.animatedbottombar:library:1.0.9'` with `implementation 'com.github.Droppers:AnimatedBottomBar:1.0.9'` and removing `jcenter()`. I then get this error when opening the app:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bandev.buddhaquotes/org.bandev.buddhaquotes.activities.Main}: android.view.InflateException: Binary XML file line #40 in org.bandev.buddhaquotes:layout/main_activity: Binary XML file line #40 in org.bandev.buddhaquotes:layout/main_activity: Error inflating class nl.joery.animatedbottombar.AnimatedBottomBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Binary XML file line #40 in org.bandev.buddhaquotes:layout/main_activity: Binary XML file line #40 in org.bandev.buddhaquotes:layout/main_activity: Error inflating class nl.joery.animatedbottombar.AnimatedBottomBar
     Caused by: android.view.InflateException: Binary XML file line #40 in org.bandev.buddhaquotes:layout/main_activity: Error inflating class nl.joery.animatedbottombar.AnimatedBottomBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at org.bandev.buddhaquotes.databinding.MainActivityBinding.inflate(MainActivityBinding.java:60)
        at org.bandev.buddhaquotes.databinding.MainActivityBinding.inflate(MainActivityBinding.java:54)
        at org.bandev.buddhaquotes.activities.Main.onCreate(Main.kt:88)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/flexbox/FlexboxLayoutManager;
        at nl.joery.animatedbottombar.AnimatedBottomBar.initRecyclerView(AnimatedBottomBar.kt:233)
        at nl.joery.animatedbottombar.AnimatedBottomBar.<init>(AnimatedBottomBar.kt:51)
        at nl.joery.animatedbottombar.AnimatedBottomBar.<init>(AnimatedBottomBar.kt:31)
        at nl.joery.animatedbottombar.AnimatedBottomBar.<init>(Unknown Source:6)
        	... 27 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.flexbox.FlexboxLayoutManager" on path: DexPathList[[zip file "/data/app/org.bandev.buddhaquotes-TUh-AmFHm7FYg1endSQdAw==/base.apk"],nativeLibraryDirectories=[/data/app/org.bandev.buddhaquotes-TUh-AmFHm7FYg1endSQdAw==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 31 more
```

**Comment by Droppers** [comment]
@jackdevey AnimatedBottomBar has some dependencies such as flexbox, which are not automatically installed using Jitpack I assume.

**Comment by Droppers** [comment]
Old versions are on Maven Central now, but one of the dependencies is only available on jCenter.

I will release a new version as soon as possible with a new version.

Btw using jCenter is not a problem as they announced all artifacts will be available indefinitely.

**Comment by russellbanks** [comment]
Thank you for putting the current versions on Maven Central. I believe the dependency you're referring to is Flexbox. As of [version 3.0.0](https://github.com/google/flexbox-layout/releases/tag/3.0.0) which was released 5 days ago, it has been put onto Maven Central.

I am happy to make a pull request and do the migrations for this if that would be easiest as adding the current versions of AnimatedBottomBar from MavenCentral still alert that jCenter will required as Flexbox 2.0.1 is used in this library.

I understand that the artifacts on jCenter will be available indefinitely but it is still best practice to move away from jCenter as it has been deprecated and it ensures that future updates can be made available for this library.

**Comment by Droppers** [comment]
I noticed that version 3.0.0 has been released, I just have to configure a plugin to be able to publish a new version to Maven Central, next week I will have plenty of time for this. 

Btw, if you have any suggestions or improvements for the library, let me know!

**Comment by Droppers** [comment]
It is now fully available on Maven Central!
